src/KamiPay.HttpApi.Host/Pages/Admin/Overview.cshtml.cs
using KamiPay.Models.Admin.Overview;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;
using Volo.Abp;
using Volo.Abp.Account;

namespace KamiPay.Pages.Admin;

[Authorize]
public class OverviewModel(IProfileAppService profileAppService, IStringLocalizer<OverviewModel> localizer) : PageModel
{
    protected IStringLocalizer<OverviewModel> L { get; } = localizer;

    public UpdateProfileInput UpdateProfileInput { get; set; } = new();

    public UpdatePasswordInput UpdatePasswordInput { get; set; } = new();

    public async Task<IActionResult> OnGetAsync()
    {
        var profile = await profileAppService.GetAsync();

        UpdateProfileInput.UserName = profile.UserName;
        UpdateProfileInput.Email = profile.Email;
        UpdateProfileInput.Name = profile.Name;
        UpdateProfileInput.Surname = profile.Surname;
        UpdateProfileInput.PhoneNumber = profile.PhoneNumber;
        UpdateProfileInput.ConcurrencyStamp = profile.ConcurrencyStamp;

        return Page();
    }

    public async Task<IActionResult> OnPostUpdateProfileAsync(UpdateProfileInput updateProfileInput)
    {
        return await OnGetAsync();
    }

    public async Task<IActionResult> OnPostChangePasswordAsync(UpdatePasswordInput updatePasswordInput)
    {
        if (!ModelState.IsValid)
        {
            return await OnGetAsync();
        }

        try
        {
            await profileAppService.ChangePasswordAsync(new ChangePasswordInput
            {
                CurrentPassword = updatePasswordInput.CurrentPassword,
                NewPassword = updatePasswordInput.NewPassword,
            });

            return Redirect("/Account/Logout");
        }
        catch (BusinessException exception)
        {
            if (exception.Code?.EndsWith("PasswordMismatch") ?? false)
            {
                ModelState.AddModelError("UpdatePasswordInput.CurrentPassword", L["PasswordMismatch"]);
            }
            else
            {
                ModelState.AddModelError("UpdatePasswordInput.NewPassword", L["PasswordDoesNotMeetRequirements"]);
            }
        }

        return await OnGetAsync();
    }
}

src/KamiPay.HttpApi.Host/Pages/Admin/Settings.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KamiPay.Pages.Admin;

[Authorize]
public class SettingsModel : PageModel
{
    public void OnGet()
    {
    }
}

src/KamiPay.HttpApi.Host/Pages/Admin/Overview.cshtml
@page "{handler?}"
@using Microsoft.Extensions.Localization
@using KamiPay.Pages.Admin
@model KamiPay.Pages.Admin.OverviewModel
@inject IStringLocalizer<OverviewModel> L
@{
    Layout = "Shared/_AdminLayout";

    ViewData["PageTitle"] = L["PageTitle"];
    ViewData["PageName"] = "Overview";
}
<div class="card">
    <div class="card-header border-bottom">
        <h4 class="card-header-title">@L["BasicInfo"]</h4>
    </div>
    <div class="card-body">
        <form method="post" asp-page-handler="UpdateProfile">
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">@L["ProfilePhoto"]</label>
                <div class="col-sm-9">
                    <div class="d-flex align-items-center">
                        <label class="avatar avatar-xl avatar-circle" for="avatarUploader">
                            <img id="avatar-image" class="avatar-img" src="~/images/kamipay.jpg" alt="Profile picture">
                        </label>
                        <div class="d-grid d-sm-flex gap-2 ms-4">
                            <div class="form-attachment-btn btn btn-primary btn-sm">
                                @L["UploadPhoto"]
                                <input type="file" class="js-file-attach form-attachment-btn-label" id="avatarUploader"
                                       data-hs-file-attach-options='{"textTarget": "#avatar-image", "mode": "image", "targetAttr": "src", "resetTarget": ".reset-btn", "resetImg": "/images/kamipay.jpg", "allowTypes": [".png", ".jpeg", ".jpg"]}'>
                            </div>
                            <button type="button" class="reset-btn btn btn-white btn-sm">@L["Delete"]</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label" asp-for="UpdateProfileInput.UserName"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control"
                           required
                           placeholder='@L["UserNameTip"]'
                           aria-label='@L["UserNameTip"]'
                           asp-for="UpdateProfileInput.UserName">
                </div>
            </div>
            <div class="row mb-4">
                <label asp-for="UpdateProfileInput.Name" class="col-sm-3 col-form-label form-label">@L["FullName"]</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <input type="text" class="form-control"
                               placeholder='@L["FirstNameTip"]'
                               aria-label='@L["FirstNameTip"]'
                               asp-for="UpdateProfileInput.Name">
                        <input type="text" class="form-control"
                               placeholder='@L["LastNameTip"]'
                               aria-label='@L["LastNameTip"]'
                               asp-for="UpdateProfileInput.Surname">
                    </div>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label" asp-for="UpdateProfileInput.Email"></label>
                <div class="col-sm-9">
                    <input type="email" class="form-control"
                           placeholder='@L["EmailAddressTip"]'
                           aria-label='@L["EmailAddressTip"]'
                           asp-for="UpdateProfileInput.Email">
                    <input type="hidden" asp-for="UpdateProfileInput.ConcurrencyStamp"/>
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3">
                <button type="submit" class="btn btn-white">@L["Cancel"]</button>
                <button type="submit" class="btn btn-primary">@L["SaveChanges"]</button>
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-header-title">@L["Password"]</h5>
    </div>
    <div class="card-body">
        <form method="post" asp-page-handler="ChangePassword">
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label" asp-for="UpdatePasswordInput.CurrentPassword"></label>
                <div class="col-sm-9">
                    <input type="password" class="form-control"
                           placeholder='@L["CurrentPasswordTip"]'
                           aria-label='@L["CurrentPasswordTip"]'
                           asp-for="UpdatePasswordInput.CurrentPassword">
                    <span class="text-danger small" asp-validation-for="UpdatePasswordInput.CurrentPassword"></span>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label" asp-for="UpdatePasswordInput.NewPassword"></label>
                <div class="col-sm-9">
                    <input type="password" class="form-control"
                           placeholder='@L["NewPasswordTip"]'
                           aria-label='@L["NewPasswordTip"]'
                           asp-for="UpdatePasswordInput.NewPassword">
                    <span class="text-danger small" asp-validation-for="UpdatePasswordInput.NewPassword"></span>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label" asp-for="UpdatePasswordInput.ConfirmPassword"></label>
                <div class="col-sm-9">
                    <div class="mb-3">
                        <input type="password" class="form-control"
                               placeholder='@L["ConfirmPasswordTip"]'
                               aria-label='@L["ConfirmPasswordTip"]'
                               asp-for="UpdatePasswordInput.ConfirmPassword">
                        <span class="text-danger small" asp-validation-for="UpdatePasswordInput.ConfirmPassword"></span>
                    </div>
                    <h5>@L["PasswordRequirements"]</h5>
                    <p class="card-text small">@L["PasswordRequirementsDesc"]</p>
                    <ul class="small">
                        <li>@L["PasswordRequirement1"]</li>
                        <li>@L["PasswordRequirement2"]</li>
                        <li>@L["PasswordRequirement3"]</li>
                        <li>@L["PasswordRequirement4"]</li>
                    </ul>
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3">
                <button type="submit" class="btn btn-white">@L["Cancel"]</button>
                <button type="submit" class="btn btn-primary">@L["SaveChanges"]</button>
            </div>
        </form>
    </div>
</div>

src/KamiPay.HttpApi.Host/Pages/Admin/Settings.cshtml
@page
@using KamiPay.Pages.Admin
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Microsoft.Extensions.Localization
@model KamiPay.Pages.Admin.SettingsModel
@inject IStringLocalizer<SettingsModel> L
@{
    Layout = "Shared/_AdminLayout";

    ViewData["PageTitle"] = L["PageTitle"];
    ViewData["PageName"] = "Settings";
}

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title">系统设置</h5>
    </div>
    <div class="card-body">
        <form>
            <div class="row mb-4">
                <label for="timeZoneLabel" class="col-sm-3 col-form-label form-label">Time zone</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="currentPassword" id="timeZoneLabel" placeholder="Your time zone" aria-label="Your time zone" value="GMT+01:00" readonly>
                </div>
            </div>
            <div class="row mb-4">
                <label for="timeZoneLabel" class="col-sm-3 col-form-label form-label">法定货币</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label for="timeZoneLabel" class="col-sm-3 col-form-label form-label">订单有效期</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">API 接口密钥</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">收款地址</label>
                <div class="col-sm-9">
                    <div class="input-group input-group-md-down-break">
                        <label class="form-control" for="genderTypeRadio1">
                            <span class="form-check">
                                <input type="radio" class="form-check-input" name="genderTypeRadio" id="genderTypeRadio1">
                                <span class="form-check-label">动态地址</span>
                            </span>
                        </label>
                        <label class="form-control" for="genderTypeRadio2">
                            <span class="form-check">
                                <input type="radio" class="form-check-input" name="genderTypeRadio" id="genderTypeRadio2" checked>
                                <span class="form-check-label">固定地址</span>
                            </span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="js-add-field row mb-4"
                 data-hs-add-field-options='{
                          "template": "#addPhoneFieldTemplate",
                          "container": "#addPhoneFieldContainer",
                          "defaultCreated": 0
                        }'>
                <label for="phoneLabel" class="col-sm-3 col-form-label form-label">固定收款地址</label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <input type="text" class="js-input-mask form-control" name="phone" id="phoneLabel" placeholder="+x(xxx)xxx-xx-xx" aria-label="+x(xxx)xxx-xx-xx"
                               data-hs-mask-options='{
                                 "mask": "+{0}(000)000-00-00"
                               }'>
                        <div class="tom-select-custom">
                            <select class="js-select form-select" name="phoneSelect"
                                    data-hs-tom-select-options='{
                                    "width": "8rem",
                                    "hideSearch": true
                                  }'>
                                <option value="Mobile" selected>TRON</option>
                                <option value="Home">EVM</option>
                            </select>
                        </div>
                    </div>
                    <div id="addPhoneFieldContainer"></div>
                    <a href="javascript:;" class="js-create-field form-link">
                        <i class="bi-plus-circle me-1"></i> 添加地址
                    </a>
                </div>
            </div>
            <div id="addPhoneFieldTemplate" style="display: none; position: relative;">
                <div class="input-group input-group-add-field">
                    <input type="text" class="js-input-mask-dynamic form-control" data-name="additionlPhone" placeholder="+x(xxx)xxx-xx-xx" aria-label="+x(xxx)xxx-xx-xx"
                           data-hs-mask-options='{
                               "mask": "+{0}(000)000-00-00"
                             }'>
                    <div class="tom-select-custom">
                        <select class="js-select-dynamic form-select" data-name="additionlPhoneSelect"
                                data-hs-tom-select-options='{
                                    "width": "8rem",
                                    "hideSearch": true
                                  }'>
                            <option value="Mobile" selected>TRON</option>
                            <option value="Home">EVM</option>
                        </select>
                    </div>
                </div>
                <a class="js-delete-field input-group-add-field-delete" href="javascript:;">
                    <i class="bi-x-lg"></i>
                </a>
            </div>

            <div class="d-flex justify-content-end gap-3 mt-3">
                <a class="btn btn-white" href="javascript:;">Cancel</a>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title">自动归集</h5>
    </div>
    <div class="card-body">
        <form>
            <div class="row  mb-4 align-items-center">
                <label for="disableAdCheckbox" class="col-sm-3 col-form-label form-label"></label>
                <div class="col-sm-9">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" >
                        <label class="form-check-label" for="disableAdCheckbox">启用自动归集</label>
                    </div>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">归集时间</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3 mt-3">
                <a class="btn btn-white" href="javascript:;">Cancel</a>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title">Telegram</h5>
    </div>
    <div class="card-body">
        <form>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">用户 ID</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">机器人密钥</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3 mt-3">
                <a class="btn btn-white" href="javascript:;">发送测试消息</a>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title">Emailing</h5>
    </div>
    <div class="card-body">
        <form>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">默认显示名称</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">默认发件人</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">主机地址</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">端口</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row  mb-4 align-items-center">
                <label for="disableAdCheckbox" class="col-sm-3 col-form-label form-label"></label>
                <div class="col-sm-9">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="disableAdCheckbox">
                        <label class="form-check-label" for="disableAdCheckbox">启用 SSL</label>
                    </div>
                </div>
            </div>
            <div class="row  mb-4 align-items-center">
                <label class="col-sm-3 col-form-label form-label"></label>
                <div class="col-sm-9">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input">
                        <label class="form-check-label">使用默认凭据</label>
                    </div>
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">用户名</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="row mb-4">
                <label class="col-sm-3 col-form-label form-label">认证密码</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control">
                </div>
            </div>
            <div class="d-flex justify-content-end gap-3 mt-3">
                <a class="btn btn-white" href="javascript:;">Send test email</a>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
    </div>
</div>